-- SQLBook: Code
CREATE DATABASE IF NOT EXISTS ecommerce_db;
USE ecommerce_db;
CREATE TABLE Category (
CategoryID INT AUTO_INCREMENT PRIMARY KEY,
CategoryName VARCHAR(100) NOT NULL,
Description TEXT
);
CREATE TABLE Seller (
SellerID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Email VARCHAR(150) NOT NULL UNIQUE,
PhoneNumber VARCHAR(15) NOT NULL,
GSTIN VARCHAR(15) NOT NULL UNIQUE,
Rating DECIMAL(2,1) DEFAULT 0.0
);
CREATE TABLE Customer (
CustomerID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
Email VARCHAR(150) NOT NULL UNIQUE,
PhoneNumber VARCHAR(15) NOT NULL
);
CREATE TABLE Address (
AddressID INT AUTO_INCREMENT PRIMARY KEY,
CustomerID INT NOT NULL,
HouseNo VARCHAR(50) NOT NULL,
Street VARCHAR(100) NOT NULL,
Landmark VARCHAR(100),
City VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
Pincode VARCHAR(10) NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Product (
ProductID INT AUTO_INCREMENT PRIMARY KEY,
Title VARCHAR(200) NOT NULL,
Price DECIMAL(10,2) NOT NULL,
StockQuantity INT NOT NULL DEFAULT 0,
SellerID INT NOT NULL,
CategoryID INT NULL,
FOREIGN KEY (SellerID) REFERENCES Seller(SellerID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
ON DELETE SET NULL
ON UPDATE CASCADE
);
CREATE TABLE Electronics (
ProductID INT PRIMARY KEY,
Brand VARCHAR(100) NOT NULL,
ModelNo VARCHAR(100) NOT NULL,
WarrantyPeriod VARCHAR(50),
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Clothing (
ProductID INT PRIMARY KEY,
Size VARCHAR(20) NOT NULL,
Color VARCHAR(50) NOT NULL,
Material VARCHAR(50),
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Grocery (
ProductID INT PRIMARY KEY,
FSSAI_LicNo VARCHAR(14) NOT NULL,
ExpiryDate DATE NOT NULL,
IsPerishable BOOLEAN NOT NULL DEFAULT TRUE,
GenderTarget VARCHAR(20),
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE `Order` (
OrderID INT AUTO_INCREMENT PRIMARY KEY,
CustomerID INT NULL,
AddressID INT NULL,
OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
TotalAmount DECIMAL(10,2) NOT NULL,
Status VARCHAR(50) NOT NULL DEFAULT 'Placed',
FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
ON DELETE SET NULL
ON UPDATE CASCADE,
FOREIGN KEY (AddressID) REFERENCES Address(AddressID)
ON DELETE SET NULL
ON UPDATE CASCADE
);
CREATE TABLE OrderItem (
OrderID INT NOT NULL,
ItemNo INT NOT NULL,
ProductID INT NULL,
Quantity INT NOT NULL CHECK (Quantity > 0),
UnitPrice DECIMAL(10,2) NOT NULL,
Subtotal DECIMAL(10,2) NOT NULL,
PRIMARY KEY (OrderID, ItemNo),
FOREIGN KEY (OrderID) REFERENCES `Order`(OrderID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
ON DELETE SET NULL
ON UPDATE CASCADE
);
CREATE TABLE Payment (
PaymentID INT AUTO_INCREMENT PRIMARY KEY,
OrderID INT NOT NULL,
TransactionID VARCHAR(100) NOT NULL UNIQUE,
Amount DECIMAL(10,2) NOT NULL,
PaymentMethod VARCHAR(50) NOT NULL,
PaymentStatus VARCHAR(50) NOT NULL DEFAULT 'Pending',
PaymentDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (OrderID) REFERENCES `Order`(OrderID)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Delivery (
DeliveryID INT AUTO_INCREMENT PRIMARY KEY,
OrderID INT NOT NULL,
AddressID INT NULL,
TrackingNumber VARCHAR(100) NOT NULL UNIQUE,
Status VARCHAR(50) NOT NULL DEFAULT 'In-Transit',
ExpectedDate DATE,
DeliveryDate DATE,
FOREIGN KEY (OrderID) REFERENCES `Order`(OrderID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (AddressID) REFERENCES Address(AddressID)
ON DELETE SET NULL
ON UPDATE CASCADE
);
-- SQLBook: Code
